
/*    +-----------------------------------------------------------------------+    */
/*    |    Do not edit this file directly.                                    |    */
/*    |    It was copied by redundancyJS.                                     |    */
/*    |    To modify it, first edit the source file (see redundancy.json).    |    */
/*    |    Then, run "npx redundancyjs" in the terminal.                      |    */
/*    +-----------------------------------------------------------------------+    */

/* do not edit */ 
/* do not edit */
/* do not edit */ 
/* do not edit */   export class Ticket {
/* do not edit */     
/* do not edit */     public id: number;
/* do not edit */
/* do not edit */     
/* do not edit */     public guid: string;
/* do not edit */
/* do not edit */     
/* do not edit */     public name: string;
/* do not edit */
/* do not edit */     
/* do not edit */     
/* do not edit */     public createdAt: string;
/* do not edit */
/* do not edit */     
/* do not edit */     
/* do not edit */     public updatedAt: Date;
/* do not edit */
/* do not edit */     
/* do not edit */     public activated: boolean;
/* do not edit */   }
/* do not edit */