
/*    +-----------------------------------------------------------------------+    */
/*    |    Do not edit this file directly.                                    |    */
/*    |    It was copied by redundancyJS.                                     |    */
/*    |    To modify it, first edit the source file (see redundancy.json).    |    */
/*    |    Then, run "npx redundancyjs" in the terminal.                      |    */
/*    +-----------------------------------------------------------------------+    */

/* do not edit */ 
/* do not edit */
/* do not edit */ 
/* do not edit */ export class User {
/* do not edit */     
/* do not edit */     public id: number;
/* do not edit */
/* do not edit */     
/* do not edit */     public teacher: string;
/* do not edit */
/* do not edit */     
/* do not edit */     public teacherShort: string;
/* do not edit */
/* do not edit */     
/* do not edit */     public grade: string;
/* do not edit */
/* do not edit */     
/* do not edit */     public course: string;
/* do not edit */
/* do not edit */     
/* do not edit */     public language: "latein" | "französisch" | "gemischt";
/* do not edit */
/* do not edit */     
/* do not edit */     public uebergang: boolean;
/* do not edit */
/* do not edit */     
/* do not edit */     public branch: "sprachlich" | "naturwissenschaftlich" | "gemischt";
/* do not edit */
/* do not edit */     
/* do not edit */     public room: number;
/* do not edit */
/* do not edit */     
/* do not edit */     public classSize: number;
/* do not edit */
/* do not edit */     
/* do not edit */     public order: {
/* do not edit */         [id: number] : number;
/* do not edit */     }
/* do not edit */
/* do not edit */     
/* do not edit */     public orderSubmitted: boolean;
/* do not edit */
/* do not edit */     
/* do not edit */     public orderDone: boolean;
/* do not edit */
/* do not edit */     
/* do not edit */     public orderAccepted: boolean;
/* do not edit */
/* do not edit */     
/* do not edit */     public orderTimestamp: Date;
/* do not edit */
/* do not edit */     
/* do not edit */     public handoverCode: string;
/* do not edit */
/* do not edit */     public token?: string;
/* do not edit */ }
/* do not edit */