
/*    +-----------------------------------------------------------------------+    */
/*    |    Do not edit this file directly.                                    |    */
/*    |    It was copied by redundancyJS.                                     |    */
/*    |    To modify it, first edit the source file (see redundancy.json).    |    */
/*    |    Then, run "npx redundancyjs" in the terminal.                      |    */
/*    +-----------------------------------------------------------------------+    */

/* do not edit */
/* do not edit */
/* do not edit */
/* do not edit */ export class Book {
/* do not edit */     
/* do not edit */     public id: number;
/* do not edit */
/* do not edit */     
/* do not edit */     public name: string;
/* do not edit */
/* do not edit */     
/* do not edit */     public publisher: string;
/* do not edit */
/* do not edit */     
/* do not edit */     public subject: string;
/* do not edit */
/* do not edit */     
/* do not edit */     public short: string;
/* do not edit */
/* do not edit */     
/* do not edit */     public comment: string;
/* do not edit */
/* do not edit */     
/* do not edit */     public language: string;
/* do not edit */
/* do not edit */     
/* do not edit */     public branch: string;
/* do not edit */
/* do not edit */     
/* do not edit */     public uebergang: boolean;
/* do not edit */
/* do not edit */     
/* do not edit */     public 5: boolean;
/* do not edit */
/* do not edit */     
/* do not edit */     public 6: boolean;
/* do not edit */
/* do not edit */     
/* do not edit */     public 7: boolean;
/* do not edit */
/* do not edit */     
/* do not edit */     public 8: boolean;
/* do not edit */
/* do not edit */     
/* do not edit */     public 9: boolean;
/* do not edit */
/* do not edit */     
/* do not edit */     public 10: boolean;
/* do not edit */
/* do not edit */     
/* do not edit */     public Q11: boolean;
/* do not edit */
/* do not edit */     
/* do not edit */     public Q12: boolean;
/* do not edit */
/* do not edit */     
/* do not edit */     public Q13: boolean;
/* do not edit */
/* do not edit */     public alert?: string;
/* do not edit */
/* do not edit */     public number?: number;
/* do not edit */
/* do not edit */     public editing?: boolean;
/* do not edit */ }
/* do not edit */